// Auto-generated by an AI, check for accuracy
declare global {
  export interface IVaultApi {
    getVaultPath: () => Promise<string | undefined>;
    selectNativeFolder: () => Promise<string | undefined>;
    saveVaultDirectory: (path: string) => Promise<{
      success: boolean;
      path?: string;
      error?: string;
    }>;
    onShowVaultSetupDialog: (callback: () => void) => () => void; // Returns a cleanup function
    onVaultReady: (callback: (path: string) => void) => () => void; // Returns a cleanup function
    onVaultSetSuccess: (callback: () => void) => () => void; // Returns a cleanup function
  }

  interface Window {
    // Define electronAPI if its structure is known, otherwise use a generic type or 'unknown'
    // For example, if @electron-toolkit/preload exposes specific functions:
    // electron: {
    //   openPath: (path: string) => Promise<void>;
    //   // ... other functions from electronAPI
    // };
    electron: unknown;
    api: IVaultApi;
  }
}

// Removed "export {};" to ensure this file is treated as a script for global augmentation
