/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as FoldersFolderSlugImport } from './routes/folders/$folderSlug'
import { Route as FoldersFolderSlugEditImport } from './routes/folders/$folderSlug.edit'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FoldersFolderSlugRoute = FoldersFolderSlugImport.update({
  id: '/folders/$folderSlug',
  path: '/folders/$folderSlug',
  getParentRoute: () => rootRoute,
} as any)

const FoldersFolderSlugEditRoute = FoldersFolderSlugEditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => FoldersFolderSlugRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/folders/$folderSlug': {
      id: '/folders/$folderSlug'
      path: '/folders/$folderSlug'
      fullPath: '/folders/$folderSlug'
      preLoaderRoute: typeof FoldersFolderSlugImport
      parentRoute: typeof rootRoute
    }
    '/folders/$folderSlug/edit': {
      id: '/folders/$folderSlug/edit'
      path: '/edit'
      fullPath: '/folders/$folderSlug/edit'
      preLoaderRoute: typeof FoldersFolderSlugEditImport
      parentRoute: typeof FoldersFolderSlugImport
    }
  }
}

// Create and export the route tree

interface FoldersFolderSlugRouteChildren {
  FoldersFolderSlugEditRoute: typeof FoldersFolderSlugEditRoute
}

const FoldersFolderSlugRouteChildren: FoldersFolderSlugRouteChildren = {
  FoldersFolderSlugEditRoute: FoldersFolderSlugEditRoute,
}

const FoldersFolderSlugRouteWithChildren =
  FoldersFolderSlugRoute._addFileChildren(FoldersFolderSlugRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/folders/$folderSlug': typeof FoldersFolderSlugRouteWithChildren
  '/folders/$folderSlug/edit': typeof FoldersFolderSlugEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/folders/$folderSlug': typeof FoldersFolderSlugRouteWithChildren
  '/folders/$folderSlug/edit': typeof FoldersFolderSlugEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/folders/$folderSlug': typeof FoldersFolderSlugRouteWithChildren
  '/folders/$folderSlug/edit': typeof FoldersFolderSlugEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/folders/$folderSlug'
    | '/folders/$folderSlug/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/folders/$folderSlug' | '/folders/$folderSlug/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/folders/$folderSlug'
    | '/folders/$folderSlug/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FoldersFolderSlugRoute: typeof FoldersFolderSlugRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FoldersFolderSlugRoute: FoldersFolderSlugRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/folders/$folderSlug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/folders/$folderSlug": {
      "filePath": "folders/$folderSlug.tsx",
      "children": [
        "/folders/$folderSlug/edit"
      ]
    },
    "/folders/$folderSlug/edit": {
      "filePath": "folders/$folderSlug.edit.tsx",
      "parent": "/folders/$folderSlug"
    }
  }
}
ROUTE_MANIFEST_END */
