/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as FoldersFolderSlugIndexImport } from './routes/folders/$folderSlug/index'
import { Route as FoldersFolderSlugEditImport } from './routes/folders/$folderSlug.edit'
import { Route as FoldersFolderSlugPromptSlugImport } from './routes/folders/$folderSlug/$promptSlug'
import { Route as FoldersFolderSlugPromptSlugEditImport } from './routes/folders/$folderSlug/$promptSlug/edit'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FoldersFolderSlugIndexRoute = FoldersFolderSlugIndexImport.update({
  id: '/folders/$folderSlug/',
  path: '/folders/$folderSlug/',
  getParentRoute: () => rootRoute,
} as any)

const FoldersFolderSlugEditRoute = FoldersFolderSlugEditImport.update({
  id: '/folders/$folderSlug/edit',
  path: '/folders/$folderSlug/edit',
  getParentRoute: () => rootRoute,
} as any)

const FoldersFolderSlugPromptSlugRoute =
  FoldersFolderSlugPromptSlugImport.update({
    id: '/folders/$folderSlug/$promptSlug',
    path: '/folders/$folderSlug/$promptSlug',
    getParentRoute: () => rootRoute,
  } as any)

const FoldersFolderSlugPromptSlugEditRoute =
  FoldersFolderSlugPromptSlugEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => FoldersFolderSlugPromptSlugRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/folders/$folderSlug/$promptSlug': {
      id: '/folders/$folderSlug/$promptSlug'
      path: '/folders/$folderSlug/$promptSlug'
      fullPath: '/folders/$folderSlug/$promptSlug'
      preLoaderRoute: typeof FoldersFolderSlugPromptSlugImport
      parentRoute: typeof rootRoute
    }
    '/folders/$folderSlug/edit': {
      id: '/folders/$folderSlug/edit'
      path: '/folders/$folderSlug/edit'
      fullPath: '/folders/$folderSlug/edit'
      preLoaderRoute: typeof FoldersFolderSlugEditImport
      parentRoute: typeof rootRoute
    }
    '/folders/$folderSlug/': {
      id: '/folders/$folderSlug/'
      path: '/folders/$folderSlug'
      fullPath: '/folders/$folderSlug'
      preLoaderRoute: typeof FoldersFolderSlugIndexImport
      parentRoute: typeof rootRoute
    }
    '/folders/$folderSlug/$promptSlug/edit': {
      id: '/folders/$folderSlug/$promptSlug/edit'
      path: '/edit'
      fullPath: '/folders/$folderSlug/$promptSlug/edit'
      preLoaderRoute: typeof FoldersFolderSlugPromptSlugEditImport
      parentRoute: typeof FoldersFolderSlugPromptSlugImport
    }
  }
}

// Create and export the route tree

interface FoldersFolderSlugPromptSlugRouteChildren {
  FoldersFolderSlugPromptSlugEditRoute: typeof FoldersFolderSlugPromptSlugEditRoute
}

const FoldersFolderSlugPromptSlugRouteChildren: FoldersFolderSlugPromptSlugRouteChildren =
  {
    FoldersFolderSlugPromptSlugEditRoute: FoldersFolderSlugPromptSlugEditRoute,
  }

const FoldersFolderSlugPromptSlugRouteWithChildren =
  FoldersFolderSlugPromptSlugRoute._addFileChildren(
    FoldersFolderSlugPromptSlugRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/folders/$folderSlug/$promptSlug': typeof FoldersFolderSlugPromptSlugRouteWithChildren
  '/folders/$folderSlug/edit': typeof FoldersFolderSlugEditRoute
  '/folders/$folderSlug': typeof FoldersFolderSlugIndexRoute
  '/folders/$folderSlug/$promptSlug/edit': typeof FoldersFolderSlugPromptSlugEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/folders/$folderSlug/$promptSlug': typeof FoldersFolderSlugPromptSlugRouteWithChildren
  '/folders/$folderSlug/edit': typeof FoldersFolderSlugEditRoute
  '/folders/$folderSlug': typeof FoldersFolderSlugIndexRoute
  '/folders/$folderSlug/$promptSlug/edit': typeof FoldersFolderSlugPromptSlugEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/folders/$folderSlug/$promptSlug': typeof FoldersFolderSlugPromptSlugRouteWithChildren
  '/folders/$folderSlug/edit': typeof FoldersFolderSlugEditRoute
  '/folders/$folderSlug/': typeof FoldersFolderSlugIndexRoute
  '/folders/$folderSlug/$promptSlug/edit': typeof FoldersFolderSlugPromptSlugEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/folders/$folderSlug/$promptSlug'
    | '/folders/$folderSlug/edit'
    | '/folders/$folderSlug'
    | '/folders/$folderSlug/$promptSlug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/folders/$folderSlug/$promptSlug'
    | '/folders/$folderSlug/edit'
    | '/folders/$folderSlug'
    | '/folders/$folderSlug/$promptSlug/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/folders/$folderSlug/$promptSlug'
    | '/folders/$folderSlug/edit'
    | '/folders/$folderSlug/'
    | '/folders/$folderSlug/$promptSlug/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FoldersFolderSlugPromptSlugRoute: typeof FoldersFolderSlugPromptSlugRouteWithChildren
  FoldersFolderSlugEditRoute: typeof FoldersFolderSlugEditRoute
  FoldersFolderSlugIndexRoute: typeof FoldersFolderSlugIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FoldersFolderSlugPromptSlugRoute:
    FoldersFolderSlugPromptSlugRouteWithChildren,
  FoldersFolderSlugEditRoute: FoldersFolderSlugEditRoute,
  FoldersFolderSlugIndexRoute: FoldersFolderSlugIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/folders/$folderSlug/$promptSlug",
        "/folders/$folderSlug/edit",
        "/folders/$folderSlug/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/folders/$folderSlug/$promptSlug": {
      "filePath": "folders/$folderSlug/$promptSlug.tsx",
      "children": [
        "/folders/$folderSlug/$promptSlug/edit"
      ]
    },
    "/folders/$folderSlug/edit": {
      "filePath": "folders/$folderSlug.edit.tsx"
    },
    "/folders/$folderSlug/": {
      "filePath": "folders/$folderSlug/index.tsx"
    },
    "/folders/$folderSlug/$promptSlug/edit": {
      "filePath": "folders/$folderSlug/$promptSlug/edit.tsx",
      "parent": "/folders/$folderSlug/$promptSlug"
    }
  }
}
ROUTE_MANIFEST_END */
